baseURL = "https://pestillilab.github.io/tacademiademo/"
languageCode = "en-us"
title = "Sample Site"
theme="tacademia.hugo"
logoNav = "img/logo.svg"
mapData = '/assets/institutions.json'
[[menu.main]]
    indentifier = 'home'
    title= 'HOME'
    name="HOME"
    URL = '/'
    weight = 10
    map = true
[[menu.main]]
    indentifier = 'research'
    name= 'RESEARCH'
    URL = '/research'
    weight = 20
[[menu.main]]
    indentifier = 'publications'
    name= 'PUBLICATIONS'
    URL = '/publications'
    weight = 30
[[menu.main]]
    indentifier = 'team'
    name= 'TEAM'
    URL = '/team'
    weight = 40
[[menu.main]]
    identifier = 'news'
    name = 'NEWS'
    URL = '/news'
# [[menu.main]]
#     identifier = 'events'
#     name= 'Events'
#     URL = '/events'

[params.keys]
    googleMaps = "AIzaSyD_DdEi4sKJWYq6zIxOtJ381CtzsB8hh5o"

[params.team]
    description = "The excellent graduate and undergraduate students, postdocs, faculty and staff members of our core team, alumni and collaborators."
[params.Nav]
    logo = "img/logo.svg"

[params.Footer]
    logo = "img/footer_logo.svg"
    title= "LAB's Name"
    backgroundColor = "#F5F5F5"
    textColor = "#646464"
    boldTextColor = "#373737"
    address = [
    "Depart Name",
    "First Line of Address",
    "Second Line of Address",
    "City Name,STATE",
    "ZIP-CODE",
    "contact@email.com"
    ]
    facebook = "link"
    twitter = "link"
    github = "link"
[params.Footer.RelatedLinks]

    [params.Footer.RelatedLinks.Education]
        "Footer Link Example #1" = "."
        "Footer Link Example #2" = "."
        "Footer Link Example #3" = "."
    [params.Footer.RelatedLinks.FooterColumn]
        "Footer Link Example #1" = "."
        "Footer Link Example #2" = "."
    [params.Footer.Institutional]
        "Footer Link Example #1" = "."
        "Footer Link Example #2" = "."
